### ISSUE TITLE
Implement dynamic adding/removing sensors

### ISSUE THREAD

**Issue by SuneJepsen** [SuneJepsen/iotproject-arduino#4]

**Comment by Spiderixius** [comment]
This is accomplished by the following setup:

![image](https://user-images.githubusercontent.com/10165995/39540135-0a53b1b2-4e42-11e8-827d-b4b01e7e77df.png)


As seen in the image the URL pattern is *.com/{device}.json which allows for adding as many devices as necessary, since it will use that devices ID as the sub root node.
